# Generated by Django 5.0.6 on 2024-05-30 19:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0003_profesor_materia'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='inscripcion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clase.curso'),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Clase.curso'),
        ),
    ]
