# Generated by Django 5.0.6 on 2024-05-30 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clase', '0004_estudiante_inscripcion_estudiante_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Clase.curso'),
        ),
    ]
